const CACHE_VERSION = 'bio-sarah-v1';
const ASSETS = [
  './',
  './index.html',
  './app.js',
  './style.css',
  './config.json',
  './manifest.json',
  './data/vragen.json',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './images/5.5_fig9.jpeg',
  './images/5.1_fig1.jpeg',
  './images/5.3_fig1.jpeg',
  './images/5.2_fig1.jpeg',
  './images/5.5_fig3.jpeg',
  './images/5.5_fig6.jpeg',
  './images/5.5_fig4.jpeg',
  './images/5.4_fig1.jpeg',
  './images/5.5_fig2.jpeg',
  './images/5.5_fig10.jpeg',
  './images/5.5_fig5.jpeg',
  './images/5.5_fig1.jpeg',
  './images/5.5_fig7.jpeg',
  './images/5.5_fig11.jpeg',
  './images/5.5_fig8.jpeg',
  './images/4.4_fig2.jpeg',
  './images/4.5_fig3.jpeg',
  './images/4.7_fig4.jpeg',
  './images/4.6_fig1.jpeg',
  './images/4.7_fig1.jpeg',
  './images/4.2_fig1.jpeg',
  './images/4.2_fig2.jpeg',
  './images/4.2_fig4.jpeg',
  './images/4.0_fig1.jpeg',
  './images/4.5_fig4.jpeg',
  './images/4.3_fig1.jpeg',
  './images/4.2_fig3.jpeg',
  './images/4.7_fig3.jpeg',
  './images/4.3_fig3.jpeg',
  './images/4.3_fig2.jpeg',
  './images/4.4_fig3.jpeg',
  './images/4.7_fig2.jpeg',
  './images/4.5_fig2.jpeg',
  './images/4.4_fig1.jpeg',
  './images/4.5_fig1.jpeg',
  './images/4.1_fig1.jpeg',
  './images/3.7_fig1.jpeg',
  './images/3.7_fig3.jpeg',
  './images/3.8_fig4.jpeg',
  './images/3.7_fig5.jpeg',
  './images/3.6_fig3.jpeg',
  './images/3.6_fig1.jpeg',
  './images/3.1_fig1.jpeg',
  './images/3.8_fig2.jpeg',
  './images/3.7_fig2.jpeg',
  './images/3.4_fig1.jpeg',
  './images/3.3_fig1.jpeg',
  './images/3.5_fig1.jpeg',
  './images/3.6_fig2.jpeg',
  './images/3.8_fig3.jpeg',
  './images/3.7_fig6.jpeg',
  './images/3.7_fig4.jpeg',
  './images/3.8_fig1.jpeg',
  './images/17.3_fig1.jpeg',
  './images/17.5_fig3.jpeg',
  './images/17.6_fig5.jpeg',
  './images/17.5_fig4.jpeg',
  './images/17.5_fig1.jpeg',
  './images/17.7_fig6.jpeg',
  './images/17.4_fig2.jpeg',
  './images/17.5_fig6.jpeg',
  './images/17.4_fig4.jpeg',
  './images/17.4_fig3.jpeg',
  './images/17.4_fig7.jpeg',
  './images/17.1_fig1.jpeg',
  './images/17.7_fig5.jpeg',
  './images/17.0_fig1.jpeg',
  './images/17.4_fig1.jpeg',
  './images/17.1_fig4.jpeg',
  './images/17.1_fig2.jpeg',
  './images/17.2_fig1.jpeg',
  './images/17.7_fig2.jpeg',
  './images/17.4_fig6.jpeg',
  './images/17.2_fig3.jpeg',
  './images/17.7_fig4.jpeg',
  './images/17.6_fig2.jpeg',
  './images/17.5_fig5.jpeg',
  './images/17.3_fig2.jpeg',
  './images/17.6_fig4.jpeg',
  './images/17.3_fig3.jpeg',
  './images/17.2_fig2.jpeg',
  './images/17.1_fig3.jpeg',
  './images/17.1_fig6.jpeg',
  './images/17.6_fig3.jpeg',
  './images/17.7_fig1.jpeg',
  './images/17.4_fig5.jpeg',
  './images/17.8_fig1.jpeg',
  './images/17.7_fig7.jpeg',
  './images/17.7_fig3.jpeg',
  './images/17.5_fig7.jpeg',
  './images/17.1_fig7.jpeg',
  './images/17.7_fig8.jpeg',
  './images/17.6_fig1.jpeg',
  './images/17.1_fig5.jpeg',
  './images/17.5_fig2.jpeg'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE_VERSION).then(c => c.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys.filter(k => k !== CACHE_VERSION).map(k => caches.delete(k))
    ))
  );
  self.clients.claim();
});

self.addEventListener('fetch', e => {
  e.respondWith(
    caches.match(e.request).then(r => r || fetch(e.request))
  );
});
